ZCS-18921: updated steps to publish

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -111,6 +111,34 @@ jobs:
             - zm-mailbox
             - zm-pkg-tool
             - .zcs-deps
+  publish_jars:
+    <<: *default_environment_settings
+    circleci_ip_ranges: true
+    steps:
+      - *default_attach_workspace
+      - run:
+          name: Prepare ant-contrib jar for root build.xml
+          command: |
+            sudo apt-get update; sudo apt-get install ant-contrib -y
+            mkdir -p ~/.ivy2/cache
+            mkdir -p ~/.zcs-deps
+            if [ -f /usr/share/java/ant-contrib.jar ]; then
+              cp -f /usr/share/java/ant-contrib.jar ~/.zcs-deps/ant-contrib-1.0b1.jar
+            elif [ -f /usr/share/ant/lib/ant-contrib.jar ]; then
+              cp -f /usr/share/ant/lib/ant-contrib.jar ~/.zcs-deps/ant-contrib-1.0b1.jar
+            else
+              echo "ant-contrib.jar not found on runner" && exit 1
+            fi
+      - run:
+          name: Validate Nexus env variables
+          command: |
+            [ -n "$NEXUS_BASE_URL" ] || (echo "NEXUS_BASE_URL is required" && exit 1)
+            [ -n "$NEXUS_USER" ] || (echo "NEXUS_USER is required" && exit 1)
+            [ -n "$NEXUS_PASSWORD" ] || (echo "NEXUS_PASSWORD is required" && exit 1)
+      - run:
+          name: Publish built jars to Nexus
+          command: |
+            JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH ant publish-remote-all
   publish_packages:
     <<: *default_environment_settings
     circleci_ip_ranges: true
@@ -138,7 +166,6 @@ jobs:
       - run:
           name: Publish built packages to Nexus APT/Yum
           command: |
-            JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH ant publish-remote-all
             JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH ant publish-remote-package
   test:
     <<: *default_environment_settings
@@ -226,6 +253,13 @@ workflows:
           <<: *filter_branches
           context:
             - docker-dev-registry
+      - publish_jars:
+          requires:
+            - test
+          <<: *filter_branches
+          context:
+            - docker-dev-registry
+            - nexus-artifactory
       - publish_packages:
           requires:
             - test
